# Generated by Django 3.2.7 on 2021-09-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_alter_school_name_of_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='number_of_students',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
