# Generated by Django 3.2.7 on 2021-10-04 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill', '0011_auto_20211004_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('department', models.CharField(max_length=225)),
                ('age', models.IntegerField(default=0)),
                ('course_to_take', multiselectfield.db.fields.MultiSelectField(choices=[('Web design and development', 'Web design and development'), ('Photography and editing', 'Photography and editing'), ('Cinematography', 'Cinematography'), ('Fashion design expert', 'Fashion design expert'), ('Digital marketing specialist', 'Digital marketing specialist'), ('Creative graphics design', 'Creative graphics design'), ('IT support and solution master', 'IT support and solution master'), ('Data analyst', 'Data analyst'), ('Cake and confectionaries', 'Cake and confectionaries'), ('Copy writing mastery', 'Copy writing mastery'), ('Complete cosmetology', 'Complete cosmetology'), ('Professional animation maker and motion graphics', 'Professional animation maker and motion graphics'), ('Hair dressing and wig making', 'Hair dressing and wig making')], max_length=330)),
                ('office', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
